version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12
    steps:
        - checkout
        - run:
              name: Echo Hello World
              command: echo hello World
